---
# Oracle Database Refresh Lab Automation
# This playbook provides a menu-driven interface to run the lab scripts

- name: Oracle Pure Storage Database Refresh Lab Automation
  hosts: oracle2
  become: yes
  become_user: oracle
  gather_facts: no
  
  vars:
    script_dir: /home/oracle/lab/lab1/bash
    oracle_home: /u01/app/oracle/product/19.0.0/dbhome_1
    grid_home: /u01/app/19.0.0/grid
    oracle_sid: orcl
    
  tasks:
    - name: Check available scripts
      find:
        paths: "{{ script_dir }}"
        patterns: "*.sh"
      register: lab_scripts
      
    - name: Display available lab scripts
      debug:
        msg:
          - "=== Available Lab Scripts ==="
          - "{% for script in lab_scripts.files %}{{ script.path | basename }}{% if not loop.last %}, {% endif %}{% endfor %}"
          
    - name: Choose execution mode
      pause:
        prompt: |
          
          Choose execution mode:
          1. Run complete refresh (refresh.sh)
          2. Run step by step
          3. Run individual script
          
          Enter choice (1-3)
      register: execution_mode
      
    - name: Execute based on choice
      include_tasks: "{{ execution_task }}"
      vars:
        execution_task: >-
          {%- if execution_mode.user_input == '1' -%}
          run_complete_refresh.yml
          {%- elif execution_mode.user_input == '2' -%}
          run_step_by_step.yml
          {%- elif execution_mode.user_input == '3' -%}
          run_individual_script.yml
          {%- else -%}
          invalid_choice.yml
          {%- endif -%}

---
# run_complete_refresh.yml
- name: Run complete refresh script
  shell: |
    cd {{ script_dir }}
    ./refresh.sh
  register: refresh_output
  environment:
    ORACLE_HOME: "{{ oracle_home }}"
    GRID_HOME: "{{ grid_home }}"
    ORACLE_SID: "{{ oracle_sid }}"
    PATH: "{{ oracle_home }}/bin:{{ grid_home }}/bin:{{ ansible_env.PATH }}"
    
- name: Display output
  debug:
    msg: "{{ refresh_output.stdout_lines }}"

---
# run_step_by_step.yml
- name: Run refresh step by step
  include_tasks: execute_script.yml
  vars:
    script_name: "{{ item }}"
    script_env: "{{ env_mapping[item] | default({}) }}"
  loop:
    - insert_demo_rec.sh
    - shutdown.sh
    - dismount_asm.sh
    - pure_snap.sh
    - mount_asm.sh
    - startup.sh
    - show_demo_rec.sh
  vars:
    env_mapping:
      insert_demo_rec.sh:
        ORACLE_HOME: "{{ oracle_home }}"
        ORACLE_SID: "{{ oracle_sid }}"
      shutdown.sh:
        ORACLE_HOME: "{{ oracle_home }}"
        ORACLE_SID: "{{ oracle_sid }}"
      dismount_asm.sh:
        ORACLE_HOME: "{{ grid_home }}"
        ORACLE_SID: "+ASM"
      mount_asm.sh:
        ORACLE_HOME: "{{ grid_home }}"
        ORACLE_SID: "+ASM"
      startup.sh:
        ORACLE_HOME: "{{ oracle_home }}"
        ORACLE_SID: "{{ oracle_sid }}"
      show_demo_rec.sh:
        ORACLE_HOME: "{{ oracle_home }}"
        ORACLE_SID: "{{ oracle_sid }}"

---
# execute_script.yml
- name: Execute script {{ script_name }}
  block:
    - name: Confirm execution of {{ script_name }}
      pause:
        prompt: "Press Enter to execute {{ script_name }} (or Ctrl+C to abort)"
        
    - name: Run {{ script_name }}
      shell: |
        cd {{ script_dir }}
        ./{{ script_name }}
      register: script_output
      environment: "{{ script_env | combine({'PATH': oracle_home + '/bin:' + grid_home + '/bin:' + ansible_env.PATH}) }}"
      
    - name: Display output of {{ script_name }}
      debug:
        msg: "{{ script_output.stdout_lines }}"
        
    - name: Check if script succeeded
      debug:
        msg: "✓ {{ script_name }} completed successfully"
      when: script_output.rc == 0
      
    - name: Script failed
      fail:
        msg: "✗ {{ script_name }} failed with return code {{ script_output.rc }}"
      when: script_output.rc != 0

---
# run_individual_script.yml  
- name: List available scripts
  debug:
    msg: "{{ lab_scripts.files | map(attribute='path') | map('basename') | list | to_nice_yaml }}"
    
- name: Choose script to run
  pause:
    prompt: "Enter the script name to run (e.g., show_demo_rec.sh)"
  register: chosen_script
  
- name: Check if script exists
  stat:
    path: "{{ script_dir }}/{{ chosen_script.user_input }}"
  register: script_check
  
- name: Run chosen script
  shell: |
    cd {{ script_dir }}
    ./{{ chosen_script.user_input }}
  register: individual_output
  environment:
    ORACLE_HOME: "{{ oracle_home }}"
    GRID_HOME: "{{ grid_home }}"
    ORACLE_SID: "{{ oracle_sid }}"
    PATH: "{{ oracle_home }}/bin:{{ grid_home }}/bin:{{ ansible_env.PATH }}"
  when: script_check.stat.exists
  
- name: Display output
  debug:
    msg: "{{ individual_output.stdout_lines }}"
  when: script_check.stat.exists
  
- name: Script not found
  fail:
    msg: "Script {{ chosen_script.user_input }} not found in {{ script_dir }}"
  when: not script_check.stat.exists

---
# invalid_choice.yml
- name: Invalid choice
  fail:
    msg: "Invalid choice: {{ execution_mode.user_input }}. Please run the playbook again and choose 1, 2, or 3."
