---
# Oracle Database Refresh Lab – Pure Storage FlashArray (No DB stop/start)

- name: Oracle DB Refresh Automation - FlashArray Only
  hosts: all
  gather_facts: no
  vars_files:
    - group_vars/all/vault.yml

  tasks:

  ##############################################################
  # 1️⃣ Insert verification record into the Source DB (optional)
  ##############################################################
  - name: Insert verification record into Source DB
    delegate_to: oracle1
    become: yes
    become_user: oracle
    shell: |
      . {{ oracle_env_file }}
      sqlplus -s / as sysdba <<EOF
      create table refresh_check (check_time date);
      insert into refresh_check values (sysdate);
      commit;
      exit;
      EOF

  ##############################################################
  # 2️⃣ Log in to the FlashArray using username/password
  ##############################################################
  - name: Login to FlashArray
    delegate_to: localhost
    shell: |
      echo "{{ pure_password }}" | pureadmin create --username {{ pure_username }} --array {{ pure_array_hostname }}
    register: login_result
    changed_when: "'Created configuration' in login_result.stdout or 'already exists' in login_result.stdout"

  - name: Confirm FlashArray login
    delegate_to: localhost
    debug:
      var: login_result.stdout_lines

  ##############################################################
  # 3️⃣ Create a snapshot of the Source Protection Group
  ##############################################################
  - name: Create snapshot of Source Protection Group
    delegate_to: localhost
    command: purepgroup snap {{ source_pgroup }}
    register: snap_result

  - debug:
      var: snap_result.stdout_lines
    delegate_to: localhost

  ##############################################################
  # 4️⃣ Identify latest snapshot name
  ##############################################################
  - name: Get latest snapshot name
    delegate_to: localhost
    shell: |
      purepgroup list --snap {{ source_pgroup }} --sort "created:-" --limit 1 --csv | tail -n 1 | cut -d, -f1
    register: latest_snapshot_name

  - debug:
      msg: "Latest snapshot: {{ latest_snapshot_name.stdout.strip() }}"
    delegate_to: localhost

  ##############################################################
  # 5️⃣ Overwrite Clone Volumes from Snapshot
  ##############################################################
  - name: Get list of Clone volumes
    delegate_to: localhost
    shell: |
      purepgroup list {{ clone_pgroup }} --volumes --csv | tail -n +2 | cut -d, -f1
    register: clone_volumes

  - name: Display Clone Volumes
    delegate_to: localhost
    debug:
      var: clone_volumes.stdout_lines

  - name: Overwrite Clone Volumes from Snapshot
    delegate_to: localhost
    loop: "{{ clone_volumes.stdout_lines }}"
    loop_control:
      loop_var: clone_vol
    shell: |
      purevol overwrite --source {{ latest_snapshot_name.stdout.strip() }}.{{ clone_vol | basename }} {{ clone_vol }}
    register: overwrite_result
    ignore_errors: yes

  - name: Show overwrite results
    delegate_to: localhost
    debug:
      var: overwrite_result.results

  ##############################################################
  # 6️⃣ Mount ASM and verify Clone DB (manual or via existing scripts)
  ##############################################################
  - name: Run mount_asm.sh script
    delegate_to: oracle2
    become: yes
    become_user: oracle
    shell: |
      cd /home/oracle/lab/lab1/bash
      ./mount_asm.sh

  - name: Verify Clone DB record using show_demo_rec.sh
    delegate_to: oracle2
    become: yes
    become_user: oracle
    shell: |
      cd /home/oracle/lab/lab1/bash
      ./show_demo_rec.sh
    register: verify_result

  - name: Show verification result
    delegate_to: oracle2
    debug:
      var: verify_result.stdout_lines

  ##############################################################
  # ✅ Done
  ##############################################################
  - name: Refresh Completed
    debug:
      msg: "Snapshot and volume overwrite completed successfully. Please start Oracle DB manually on clone host and verify record."

