---
# Oracle Database Refresh Lab – Single Host Automation (oracle2)
# All refresh steps are executed locally on oracle2 using the lab scripts.

- name: "Oracle DB Refresh Automation – Run all scripts on oracle2"
  hosts: oracle2
  gather_facts: no

  vars:
    oracle_user: oracle
    lab_script_path: /home/oracle/lab/lab1/bash

  tasks:
  ##########################################################################
  # 1️⃣ Insert demo record in Prod DB (handled remotely inside script)
  ##########################################################################
  
  - name: Insert verification record in Prod DB
    become: yes
    become_user: "{{ oracle_user }}"
    shell: |
      . /home/oracle/lab/lab1/bash/env_oracle.sh
      cd {{ lab_script_path }}
      ./insert_demo_rec.sh
    register: insert_result

  - debug:
      var: insert_result.stdout_lines

 ##########################################################################
  # this is the freeze EPIC DB
  # 2️⃣ Shutdown Prod DB
  ##########################################################################
  - name: Stop Prod DB
    become: yes
    become_user: "{{ oracle_user }}"
    shell: |
      . /home/oracle/lab/lab1/bash/env_oracle.sh
      cd {{ lab_script_path }}
      ./startup.sh
      ./shutdown.sh
    register: shutdown_result

  - debug:
      var: shutdown_result.stdout_lines

  ##########################################################################
  # 3️⃣ Dismount ASM Disk Groups
  ##########################################################################
  - name: Dismount ASM disk groups
    become: yes
    become_user: "{{ oracle_user }}"
    shell: |
      . /home/oracle/lab/lab1/bash/env_oracle.sh
      cd {{ lab_script_path }}
      ./dismount_asm.sh
    register: dismount_result

  - debug:
      var: dismount_result.stdout_lines

  ##########################################################################
  # 4️⃣ Take Snapshot and Refresh Backup 
  ##########################################################################
  - name: Take snapshot and refresh Backup
    become: yes
    become_user: "{{ oracle_user }}"
    shell: |
      . /home/oracle/lab/lab1/bash/env_oracle.sh
      cd {{ lab_script_path }}
      ./pure_snap.sh
    register: snap_refresh_result

  - debug:
      var: snap_refresh_result.stdout_lines

  ##########################################################################
  
  # 5️⃣ Mount ASM and Start Backup DB
  ##########################################################################
  - name: Mount ASM and start Backup DB
    become: yes
    become_user: "{{ oracle_user }}"
    shell: |
      . /home/oracle/lab/lab1/bash/env_oracle.sh
      cd {{ lab_script_path }}
      ./mount_asm.sh
      ./startup.sh
    register: startup_result

  - debug:
      var: startup_result.stdout_lines

  ##########################################################################
  # 6️⃣ Verify Record in Backup DB
  ##########################################################################
  - name: Verify record in refreshed Backup DB
    become: yes
    become_user: "{{ oracle_user }}"
    shell: |
      cd {{ lab_script_path }}
      ./show_demo_rec.sh
    register: verify_result
    tags: verify

  - debug:
      var: verify_result.stdout_lines

  ##########################################################################
  # ✅ Done
  ##########################################################################
  - name: Refresh Completed
    debug:
      msg: "Oracle Refresh completed successfully on oracle2 using local lab scripts."
